[toc]

# 1.异步加载

## async和defer的区别

相同点
+ 加载文件时不阻塞页面渲染
+ 使用这两个属性的脚本中不能调用document.write方法
+ 有脚本的onload的事件回调

不同点

```js
JS引擎进行词法分析构建DOM树，到script的时候会停下来去加载JS代码，async就是在DOM解析过程异步加载js,加载完就执行，而defer要等DOM解析完成后，再去下载，如果js有前后依赖性应该使用defer
```

# 2.JS 异步解决方案的发展历程以及优缺点。

异步编程的语法目标，就是怎样让它更像同步编程。
主要方式：

+ 回调函数
+ 事件监听
+ 发布/订阅
+ Promise

+ Generator

## 1.并发和并行区别

> 并发：宏观上同时完成任务，实质上是通过任务之间的切换完成的

> 并行：实际上就是同时完成多个任务

## 2.回调函数（callback）


```js
ajax('XXX1', () => {
    // callback 函数体
    ajax('XXX2', () => {
        // callback 函数体
        ajax('XXX3', () => {
            // callback 函数体
        })
    })
})
```
优点：解决了同步的问题, 必须挨个排队执行

缺点：

+ 回调地狱,需要自己去理清楚执行顺序
+ 回调是否执行，执行了多少次,是同步还是异步执行的难以判断(内部混杂了同步异步的函数，比如如果有缓存，执行同步，没有缓存就去请求，执行异步，混杂向外只暴露一个接口)
+ 错误难以获取，不能直接使用try...catch(因为异步操作，只有一个执行上下文，难以寻找错误)
+ 不能直接return把执行结果给外层， 因为每一次只会把执行结果给调用的函数， 回调函数实际上只有最内层能拿到最终的结果

## 3.Promise

Promise就是为了解决callback的问题而产生的。实现了链式调用，也就是说每次 then 后返回的都是一个全新 Promise，如果我们在 then 中 return ，return 的结果会被 Promise.resolve() 包装

```js
ajax('XXX1')
  .then(res => {
      // 操作逻辑
      return ajax('XXX2')
  }).then(res => {
      // 操作逻辑
      return ajax('XXX3')
  }).then(res => {
      // 操作逻辑
  })
```
优点：解决了回调地狱的问题

缺点：

+ 无法捕获错误

```js
// promise的传参应该是resolve和reject两个函数， 传递null会有语法错误，代码停止运行，不能打印233333
const promise = new Promise(null);
console.log(233333);
// promise内部产生错误，会传递给默认的reject函数， promise状态变为rejected, 通过下一步的then或者catch捕获， 但是没有提供的话就会继续执行，打印2333333
let promise = new Promise(() => {
    throw new Error('error')
});
console.log(2333333);
```

+ 单一值

```js
//每次向then传递的都为单一的值，promise.all有两个promise对象， 给then的只能是一个数组
Promise.all([Promise.resolve(1), Promise.resolve(2)])
.then(([x, y]) => {
    console.log(x, y);
});
```

+ 无法取消

```
一旦开始，无法取消
```



## 4.Generator

+ 特点：生成器，可以解决回调地狱的问题，可以控制函数的执行, 在函数的某些部分停止, 可以配合 co 函数库使用, 

```js
function* helloWorldGenerator() {
  yield 'hello';
  yield 'world';
  return 'ending';
}

var hw = helloWorldGenerator();
```

```JS
hw.next()// { value: 'hello', done: false }
hw.next()// { value: 'world', done: false }
hw.next()// { value: 'ending', done: true }
hw.next()// { value: undefined, done: true }
```

`Generator函数`被调用时并不会执行，只有当调用next方法时才会执行, 即函数可以暂停，也可以恢复执行。

每次调用遍历器对象的next方法，就会返回一个有着value和`done`两个属性的对象。`value`属性表示当前的内部状态的值，是yield表达式后面那个表达式的值；`done`属性是一个布尔值，表示是否遍历结束。

以下是一个示例

+ 关键字yield来实现调用另外的Generator函数。如果一个Generator函数A执行过程中，进入（调用）了另一个Generator函数B，那么会一直等到Generator函数B全部执行完毕后，才会返回Generator函数A继续执行。

```js
function *foo(x) { 
  let y = 2 * (yield (x + 1)) 
  let z = yield (y / 3) 
  return (x + y + z) 
}
let it = foo(5)
console.log(it.next())   // => {value: 6, done: false}
console.log(it.next(12)) // => {value: 8, done: false}
console.log(it.next(13)) // => {value: 42, done: true}
```

+ 第一次调用next, 第一个 `yield` 语句 `(x + 1)` 将 `x` 增加1
+ 第二次调用next，yield输入参数12，会赋值给第一个yield处， 则y=2*12，停在yield (y / 3) ，也就是24/3=8
+ 第三次调用next, 第二个yield赋值13， 则z=13，y=24,x=5,和为42

## 5.Async/await

async、await 是异步的终极解决方案, 

优点：

+ 代码清晰，不用像 Promise 写一大堆 then 链，处理了回调地狱的问题
+  可以被try,catch捕获

缺点：await 将异步代码改造成同步代码，如果**多个异步操作没有依赖性**而使用 await 会导致性能上的降低。


```js
async function test() {
  // 以下代码没有依赖性的话，完全可以使用 Promise.all 的方式
  // 如果有依赖性的话，其实就是解决回调地狱的例子了
  await fetch('XXX1')
  await fetch('XXX2')
  await fetch('XXX3')
}
```
+ setTimeout、Promise、Async/Await 的区别

  + settimeout的回调函数放到宏任务队列里
  + promise.then里的回调函数会放到相应宏任务的微任务队列里；
  + async函数表示函数里面可能会有异步方法，await后面跟一个表达式，async方法执行时，遇到await会立即执行表达式，然后把表达式后面的代码放到微任务队列里

### 实现原理

async 是Generator函数的语法, 并进行了改进， async函数就是将 Generator 函数的星号（*）替换成async，将yield替换成await

改进的部分：

+ 无需手动执行 next() 方法
+ 语义更好理解
+ async 函数返回值是 Promise 对象





***************************
# promise

## 1.Promise基本使用

解决回调的部分问题
+ 回调执行多次===> Promise的resolve只能执行一次
+ 回调函数有没有执行===> Promise.race
+ 无法判定回调是否被执行==>then里规定了异步执行顺序

```js
new Promise((resolve, reject) => {
  resolve('success')
  // 无效
  reject('reject')
})
```

### catch

+ 捕获then的前一步里的错误，then的reject和catch作用相同
+ 捕获then里的错误，需要在下一个then或者catch里

```js
somethingAsync.then(function() {
    return somethingElseAsync()
}).then(null, function(err) {
    handleMyError(err);
});
或者
somethingAsync().then(function() {
    return somethingElseAsync();
}).catch(function(err) {
    handleMyError(err);
});

```

### promise.then

promise的then，如果有return，会被promise.resolve包裹，返回依然为promise

### promise.all

只有全部都执行才能执行，如下，如果p1,p2,p3都执行resolve，那么结果为[1,2,3],如果把p2改为reject(2),那么执行结果为2

```js
const p1 = new Promise((resolve, reject) => {
    resolve(1);
});
const p2 = new Promise((resolve, reject) => {
    resolve(2);
});
const p3 = new Promise((resolve, reject) => {
    resolve(3);
});

Promise.all([p1, p2, p3]).then(data => { 
    console.log(data); // [1, 2, 3] 结果顺序和promise实例数组顺序是一致的
}, err => {
    console.log(err);
});
```

### Promise.race

只要有一个为rejected或者resolved就执行后续操作

```js
function timerPromisefy(delay) {
    return new Promise(function (resolve, reject) {
        setTimeout(function () {
            resolve(delay);
        }, delay);
    });
}
var startDate = Date.now();

Promise.race([
    timerPromisefy(10),
    timerPromisefy(20),
    timerPromisefy(30)
]).then(function (values) {
    console.log(values); // 10
});
```

## 2.如何中断promise的执行

### 第一个then强行报错

一种方法是在then 1中直接抛错, 这样就不会执行then 2, then 3, 直接跳到catch方法打印err(但此方法并没有实际中断)

```js
Promise.resolve().then(() => {
    console.log('then 1')
    throw new Error('xxx')
}).then(() => {
    console.log('then 2')
}).then(() => {
    console.log('then 3')
}).catch((err) => {
    console.log(err)
})
```
### then 1中return 一个新的Promise

在then 1中return 一个新的Promise,但不改变其状态,这样该Promise就一直处于pedding状态,即不会执行后面任何方法，因为Promises/A+标准：原Promise对象的状态将跟新对象保持一致。


```js
Promise.resolve().then(() => {
    console.log('then 1')
    return new Promise(() => {})
}).then(() => {
    console.log('then 2')
}).then(() => {
    console.log('then 3')
}).catch((err) => {
    console.log(err)
})
```
### Promise.race竞速方法

让其它不执行

```js
let p1 = new Promise((resolve, reject) => {
    resolve('ok1')
})
 
let p2 = new Promise((resolve, reject) => {
    setTimeout(() => {resolve('ok2')}, 10)
})
 
Promise.race([p2, p1]).then((result) => {
    console.log(result) //ok1
}).catch((error) => {
    console.log(error)
})
```



## 3.手写Promise

promise翻译是承诺，它有三种状态，状态只能从pending变为resolved或者rejected
+ pending 等待中
+ fulfilled已执行
+ rejected 已拒绝

### 基本Promise

```js
var peomise1=new Mypromise((resolve,reject)=>{
    resolve(100)
    // pending变为了resolved， 不能再执行reject了
    reject(200)
})

// 定义promise的三种状态
const PENDING='pending'
const RESOLVED='resolved'
const REJECTED='rejected'
function Mypromise(fn){
    const that = this
    that.state= PENDING  // 初始状态
    that.resolvedcallback=[] // 成功状态下的回调函数
    that.rejectedcallback=[] // 失败状态下的回调函数
    that.value=null // 用于存储传入的值

    function resolve(value){
        if(that.state=== PENDING){
            that.state=RESOLVED
            that.value=value
         that.resolvedcallback.map((cb)=>cb(that.value)}
        console.log('resolve',that.value)
    }
    function reject(value){
        if(that.state === PENDING){
            that.state=REJECTED
            that.value=value           that.rejectedcallback.map((cb)=>cb(that.value))
        }
        console.log('reject',that.value)
    }            
    try{
        fn(resolve,reject)
    }catch(e){
        reject(e)
    }
}
```
+ then

```js
观察者模式
then收集依赖，放入回调函数数组里 ->异步触发resolve -> resolve执行依赖
```


```js
Mypromise.prototype.then=function(onfullfilled,onrejected){
    const that =this
    if(that.state===PENDING){
        that.resolvedcallback.push(onfullfilled)
        that.rejectedcallback.push(onrejected)
    }
    if(that.state===RESOLVED){
        onfullfilled(that.value)
    }
    if(that.state===REJECTED){
        onrejected(that.value)
    }
}

var peomise1=new Mypromise((resolve,reject)=>{
    resolve(100)
    reject(200)
}).then(data=>{console.log(data)})
```

### 基础promise改造

#### resolve和reject函数

作用： 修改state状态，执行搜集到的回调函数

+ 改造resolve和reject函数，resolve判断是否为promise类型，是则执行then
+ resolve和reject用setTimeout包裹

```js
//resolve函数
function resolve(value) {
  //resolve判断是否为promise类型，是则执行then
  if (value instanceof MyPromise) {
      return value.then(resolve, reject) 
   } 
   setTimeout(()=>{//保证执行顺序
        //只有状态为等待中才可以进行状态改变并遍历回调函数数组
        if (that.state === PENDING) { 
            that.state = RESOLVED 
            that.value = value 
            that.resolvedCallbacks.map(cb => cb(that.value))
            console.log('resolve',value)
        }
       },0)
     } 

//reject函数
function reject(value) { 
  setTimeout(()=>{
    if (that.state === PENDING) {
      that.state = REJECTED 
      that.value = value 
      that.rejectedCallbacks.map(cb => cb(that.value))
    }
  },0)
} 
```

#### then

+ then需要支持链式调用，then返回的值需要被包裹为promise形式，才能继续调用then方法

```js
if (that.state === PENDING) { 
  // that.resolvedCallbacks.push(onFulfilled) 
  return ( promise2 = new MyPromise((resolve, reject) => { 
    that.resolvedCallbacks.push(() => { 
        try { 
            const x = onFulfilled(that.value) 
            resolutionProcedure(promise2, x, resolve, reject)
         } catch (r) { 
              reject(r) 
         } 
     }) 
  // that.rejectedCallbacks.push(onRejected) 
     that.rejectedCallbacks.push(() => { 
        try { 
            const x = onRejected(that.value)
            resolutionProcedure(promise2, x, resolve, reject)
            } catch (r) { 
              reject(r) 
           } 
      }) 
   }))
    console.log('then pending')
} 
```

####  promise状态透传

promise A+规定 then方法必须返回一个promise实例， 在 Promise 链中，如果某个 Promise 没有绑定相应的回调函数（onFulfilled 或 onRejected），那么它会将状态和值或原因传递给下一个 Promise，以确保错误不被静默丢弃， 可以被捕获和处理。

then得到的值需要进一步统一处理，实现兼容多种 Promise 的 resolutionProcedure 函数

```js
// promise2,then的我们需要的返回，x为then执行onFulfilled或onRejected返回值，可能是普通值，也可能是promise
//resolve,reject为promise2的对应resolve和reject
function resolutionProcedure(promise2, x, resolve, reject) { 
    if (promise2 === x) { 
        return reject(new TypeError('Error')) 
    } 
}
//避免巡回引用问题，promise2与x不能相等
let p = new MyPromise((resolve, reject) => { 
resolve(1)
})
let p1 = p.then(value => { return p1})
```

+ 进一步判断x的类型
+ 如果x为普通值，直接resolve
+ 如果x为promise，那么它必然有一个then方法，判断x.then的类型，如果是普通值（then链结束），resolve处理，如果为function，那么调用它的then方法，并改变调用次数的值，然后递归调用，直到最终成为一个普通值

```js
function resolutionProcedure(promise2, x, resolve, reject) { 
    if (promise2 === x) { 
        return reject(new TypeError('Error')) 
    } 
   //首先创建一个变量 called 用于判断是否已经调用过函数
    let called = false
    //判断为是函数或者对象（promise）
    if (x !== null && (typeof x === 'object' || typeof x === 'function')) { 
         try { 
            let then = x.then //判断类型
            if (typeof then === 'function') { //判断得到x.then为函数，说明它是promise里的then方法, 
              //使用x.then方法
                then.call(  x, y => { 
                  //如果已经调用过，直接返回
                  if (called) return 
                  //没有调用过，标记为调用过
                   called = true 
                  //由于成功的返回y还可能是promise，所以需要递归
                  resolutionProcedure(promise2, y, resolve, reject) 
                 }, e => {  
                     if (called) return 
                          called = true 
                          reject(e) 
                 }) 
              //判断得到x.then不为函数，直接resolve
             } else { 
                resolve(x)
             } 
         } catch (e) { 
             if (called) return 
             called = true 
             reject(e) 
           } 
    } else { 
      //不是对象或者函数（不是promise，值直接传入resolve中）
       resolve(x) 
    } 
}
```



### Promise A+

```js
// 定义promise的三种状态
const PENDING='pending'
const RESOLVED='resolved'
const REJECTED='rejected'

// 自定义promise， 接收fn作为参数， fn 包含两个参数 resolve 和 reject，分别用于在异步操作成功或失败时改变 Promise 的状态。
function MyPromise(fn){
   const that = this
   that.state= PENDING        // 初始状态
   that.resolvedCallbacks=[]  // 成功回调数组
   that.rejectedCallbacks=[]  // 失败回调数组
   that.value=null
  
  // resolve函数：用于改变状态以及保证回调函数执行
  function resolve(value) { 
    if (value instanceof MyPromise) { //值必须是promise， 执行then搜集成功的毁掉函数
      return value.then(resolve, reject) 
    } 
    setTimeout(()=>{//保证执行顺序
      if (that.state === PENDING) { 
        //只有状态为等待中才可以进行状态改变并遍历回调函数数组
        that.state = RESOLVED 
        that.value = value 
      }
    },0)
  } 
  //reject函数：用于改变状态以及保证回调函数执行
  function reject(value) { 
    setTimeout(()=>{
      if (that.state === PENDING) {
        that.state = REJECTED 
        that.value = value 
        that.rejectedCallbacks.map(cb => cb(that.value))
      }
    },0)
  } 
  
  try{
    fn(resolve,reject)
  }catch(e){
    reject(e)
  }
}

// then 搜集回调函数
MyPromise.prototype.then=function(onFulfilled,onRejected){
    const that =this
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : v => v 
    onRejected = typeof onRejected === 'function' ? onRejected : r => {throw r } 
    if (that.state === PENDING) { 
     // that.resolvedCallbacks.push(onFulfilled) 
     return ( promise2 = new MyPromise((resolve, reject) => { 
        that.resolvedCallbacks.push(() => { 
                try { 
                    const x = onFulfilled(that.value) 
                    resolutionProcedure(promise2, x, resolve, reject)
                  } catch (r) { 
                      reject(r) 
                  } 
        }) 
      // that.rejectedCallbacks.push(onRejected) 
         that.rejectedCallbacks.push(() => { 
              try { 
                  const x = onRejected(that.value)
                  resolutionProcedure(promise2, x, resolve, reject)
               } catch (r) { 
                  reject(r) 
               } 
           }) 
      }))
  } 
  
  //如果状态为resolved，执行函数
  if (that.state === RESOLVED) { 
     return (promise2 = new MyPromise((resolve, reject) => { 
       setTimeout(() => { 
          try { 
              const x = onFulfilled(that.value) 
              resolutionProcedure(promise2, x, resolve, reject) 
            } catch (reason) { 
                 reject(reason) 
             } 
         })
     })) 
  }

  // //如果状态为reject，执行函数
   if (that.state === REJECTED) { 
       return (promise2 = new MyPromise((resolve, reject) => { 
           setTimeout(() => { 
               try { 
                 const x = onRejected(that.value) 
                 resolutionProcedure(promise2, x, resolve, reject) 
                } catch (reason) { 
                    reject(reason) 
               } 
          })
      })) 
   }
 } 

// promise2,then的我们需要的返回，x为then执行onFulfilled或onRejected返回值，可能是普通值，也可能是promise
//resolve,reject为promise2的对应resolve和reject

这是一个内部函数，用于处理 Promise 的状态透传和值传递。它处理了各种情况，包括 Promise 链中的透传、返回 Promise、错误处理等。这个函数确保了 Promise/A+ 规范的要求，包括状态透传和错误处理。

function resolutionProcedure(promise2, x, resolve, reject) { 
    if (promise2 === x) { 
        return reject(new TypeError('Error')) 
    } 
    //首先创建一个变量 called 用于判断是否已经调用过函数
    let called = false 
    //判断为是函数或者对象（promise）
    if (x !== null && (typeof x === 'object' || typeof x === 'function')) {
         try { 
            // 判断得到x为函数或者对象（promise类型）
            let then = x.then //判断类型
            //判断得到x.then为函数，说明它是promise里的then方法
            if (typeof then === 'function') { 
                then.call(  x, y => { //使用x.then方法
                   if (called) return //如果已经调用过，直接返回
                    called = true //没有调用过，标记为调用过
   //由于成功的返回y还可能是promise，所以需要递归
                     resolutionProcedure(promise2, y, resolve, reject) 
                   }, e => {  
                       if (called) return 
                          called = true 
                          reject(e) 
                   }) 
             } else { //判断得到x.then不为函数，直接resolve
                resolve(x)
             } 
         } catch (e) { 
             if (called) return 
             called = true 
             reject(e) 
             } 
    } else { //不是对象或者函数（不是promise，值直接传入resolve中）
        resolve(x) 
    } 
}

const p1 = new MyPromise((resolve, reject) => {
  resolve(1)          //同步executor测试
}).then(res => {
    console.log(res)
    return 2          //链式调用测试
  })

  .then()             //值穿透测试
  .then(res => {
    console.log(res)
    return new MyPromise((resolve, reject) => {
      resolve(3)      //返回Promise测试
    })
  })
  .then(res => {
    console.log(res)
    throw new Error('reject测试')   //reject测试
  })
  .then(() => {}, err => {
    console.log(err)
  })
// 1 
// 2 
// 3 
// Error: reject测试
```

## 4.实现 promiseify 方法

作用：把异步函数转换为promise,直接可以使用then

```js
let Promise = require('./bluebird');
let fs = require("fs");

var readFile = Promise.promisify(fs.readFile);
readFile("1.txt", "utf8").then(function(data) {
    console.log(data);
})
```
写法

+ 返回一个promise
+ 内部将原来参数后面拼接一个回调函数参数，在回调函数里执行这个promise的reslove方法把结果传出去，promiseify就实现了

```js
MyPromise.promisify = function(fn) {
    return function() {
        var args = Array.from(arguments);
        return new MyPromise(function(resolve, reject) {
            fn.apply(null, args.concat(function(err) {
                err ? reject(err) : resolve(arguments[1])
            }));
        })
    }
}
```
## 5.手写race方法

+ **Promise.resolve(p)**用于处理传入值不为Promise的情况
+ 直接forEach即可
```js
let race=function(arr){
  return new Promise((resolve,reject)=>{
    arr.forEach(item=>{
      //同时执行Promise,如果有一个Promise的状态发生改变,就变更新MyPromise的状态
      Promise.resolve(item).then(resolve,reject)
    })
  })
}

let p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('success2')
    }, 1000)
})
let p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject('reject')
    }, 500)
})
// 调用
race([p1, p2]).then(res => {
    console.log(res);
}).catch(err => {
    console.error(err);
})
```

## 6.手写all方法

+ 输入是promise数组， 返回也是promise, 并且结果是传入的promise数组的结果
+ 当所有的任务都执行完成时，Promise.all()返回resolve，但当有一个失败(reject)，则返回失败的信息，即使其他promise执行成功，也会返回失败。
+ 需要先把所有方法搜集到一个数组里
+ promise.resolve()包裹
```js
function promiseAll(promises) {
  return new Promise((resolve, reject) => {
    if (!Array.isArray(promises)) {
      reject(new TypeError('promises must be an array'));
      return;
    }

    const results = [];
    let completedPromises = 0;

    promises.forEach((promise, index) => {
      Promise.resolve(promise)
        .then((result) => {
          results[index] = result;
          completedPromises++;

          if (completedPromises === promises.length) {
            resolve(results);
          }
        })
        .catch(reject);
    });

    if (promises.length === 0) {
      resolve(results);
    }
  });
}

// 示例使用
const promise1 = Promise.resolve(1);
const promise2 = new Promise((resolve) => setTimeout(() => resolve(2), 1000));
const promise3 = Promise.reject('Error occurred');

promiseAll([promise1, promise2, promise3])
  .then((results) => console.log('All promises resolved:', results))
  .catch((error) => console.error('At least one promise rejected:', error));
```
## 7.手写finally

finally()方法返回一个Promise。在promise结束时，无论结果是fulfilled或者是rejected，都会执行指定的回调函数。在finally之后，还可以继续then。并且会将值原封不动的传递给后面的then

```js
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```

```
为什么需要Promise.resolve(callback()).then(() => value)
而不能直接执行callback, return value

因为callback如果是个异步操作，返回promise呢.希望等callback执行完再接着执行
```

## 8.catch,all,resolve,reject,race

```js
//catch方法其实就是执行一下then的第二个回调
catch(rejectFn) {
  return this.then(undefined, rejectFn)
}
```

```js
//静态的resolve方法
static resolve(value) {
  if(value instanceof MyPromise) return value // 根据规范, 如果参数是Promise实例, 直接return这个实例
  return new MyPromise(resolve => resolve(value))
}
```

```js
//静态的reject方法
static reject(reason) {
  return new MyPromise((resolve, reject) => reject(reason))
}
```

# async函数(spawn的实现)

async 函数就是将 Generator 函数的星号（*）替换成 async，将 yield 替换成 await。async 函数的实现，就是将 Generator 函数和自动执行器，包装在一个函数里。

```js

async function fn(args){
 // ...
}
// 等同于
function fn(args){ 
  return spawn(function*() {
    // ...
  }); 
}
```
spawn函数的实现

```js
function spawn(genF) {
  return new Promise(function(resolve, reject) {
    var gen = genF();
    function step(nextF) {
      try {
        var next = nextF();
      } catch(e) {
        return reject(e); 
      }
      if(next.done) {
        return resolve(next.value);
      } 
      Promise.resolve(next.value).then(function(v) {
        step(function() { return gen.next(v); });      
      }, function(e) {
        step(function() { return gen.throw(e); });
      });
    }
    step(function() { return gen.next(undefined); });
  });
}
```


# async、await 细节

资料：https://juejin.cn/post/7194744938276323384#heading-1

## async的返回值

`async`函数在抛出返回值时，会根据返回值**类型**开启**不同数目的微任务**

- return结果值：非`thenable`、非`promise`（不等待）
- return结果值：`thenable`（等待 1个`then`的时间）
- return结果值：`promise`（等待 2个`then`的时间）

```js
async function testC () {
    return new Promise((resolve, reject) => {
        resolve()
    })
} 

testC().then(() => console.log(1));
Promise.resolve()
    .then(() => console.log(2))
    .then(() => console.log(3))
    .then(() => console.log(4))
// (等待两个then)最终结果: 2 3 1 4
```

## **await 右值类型区别**

+ `await`后面接非 `thenable` 类型，会立即向微任务队列添加一个微任务`then`，**但不需等待**
+ `await` 后面接 `thenable` 类型，需要**等待一个 `then` 的时间之后**执行
+ `await` 后面接 promise 类型， 需要**等待一个 `then` 的时间之后**执行（TC 39(ECMAScript标准制定者) 对`await` 后面是 `promise` 的情况如何处理进行了一次修改，**移除**了额外的两个微任务，在**早期版本**，依然会等待两个 `then` 的时间）
+  **完全可以将 `await` 后面的代码可以看做在 `then` 里面执行的结果**

```js
function func () {
    console.log(2);
}
async function test () {
    console.log(1);
    await func();
    console.log(3);
}
test();
console.log(4);

// 最终结果👉: 1 2 4 3
```

## 其他

`await`一定要等到右侧的表达式有**确切的值**才会放行，否则将一直等待（阻塞当前`async`函数内的后续代码）

```js
function func () {
    return new Promise((resolve) => {
        console.log('B')
        // resolve() 故意一直保持pending
    })
}
async function test () {
    console.log(1);
    await func()
    console.log(3);
}
test();
console.log(4);
// 最终结果👉: 1 B 4 (永远不会打印3)
```

